#!/usr/bin/env bash
#
# This file is part of REANA.
# Copyright (C) 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025 CERN.
#
# REANA is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

set -o errexit
set -o nounset

docker_build() {
    docker build -t docker.io/reanahub/reana-ui .
}

docs_sphinx() {
    sphinx-build -qnNW docs docs/_build/html
}

format_prettier() {
    (cd reana-ui && yarn && yarn prettier)
}

js_tests() {
    (cd reana-ui && yarn && yarn test --ci --passWithNoTests)
}

lint_commitlint() {
    from=${2:-master}
    to=${3:-HEAD}
    pr=${4:-[0-9]+}
    if command -v commitlint >/dev/null 2>&1; then
        commitlint --from="$from" --to="$to"
    else
        npx commitlint --from="$from" --to="$to"
    fi
    found=0
    while IFS= read -r line; do
        commit_hash=$(echo "$line" | cut -d ' ' -f 1)
        commit_title=$(echo "$line" | cut -d ' ' -f 2-)
        commit_number_of_parents=$(git rev-list --parents "$commit_hash" -n1 | awk '{print NF-1}')
        # (i) skip checking release commits generated by Release Please
        if [ "$commit_number_of_parents" -le 1 ] && echo "$commit_title" | grep -qE "^chore\(.*\): release"; then
            continue
        fi
        # (ii) check presence of PR number
        if ! echo "$commit_title" | grep -qE "\(#$pr\)$"; then
            echo "✖   Headline does not end by '(#$pr)' PR number: $commit_title"
            found=1
        fi
        # (iii) check absence of merge commits in feature branches
        if [ "$commit_number_of_parents" -gt 1 ]; then
            if echo "$commit_title" | grep -qE "^chore\(.*\): merge "; then
                break # skip checking maint-to-master merge commits
            else
                echo "✖   Merge commits are not allowed in feature branches: $commit_title"
                found=1
            fi
        fi
    done < <(git log "$from..$to" --format="%H %s")
    if [ $found -gt 0 ]; then
        exit 1
    fi
}

lint_jsonlint() {
    find . -name "*.json" ! -path "./reana-ui/node_modules/*" -exec jsonlint -q {} \+
}

lint_hadolint() {
    docker run -i --rm docker.io/hadolint/hadolint:v2.12.0 < Dockerfile
}

lint_js() {
    (cd reana-ui && yarn && yarn lint)
}

lint_shellcheck() {
    find . -name "*.sh" ! -path "./reana-ui/node_modules/*" -exec shellcheck {} \+
}

all() {
    docker_build
    docs_sphinx
    format_prettier
    js_tests
    lint_commitlint
    lint_hadolint
    lint_jsonlint
    lint_js
    lint_shellcheck
}

help() {
    echo "Usage: $0 [options]"
    echo "Options:"
    echo "  --all                Perform all checks [default]"
    echo "  --docker-build       Check Docker build"
    echo "  --docs-sphinx        Check Sphinx docs build"
    echo "  --format-prettier    Check formatting of JavaScript etc files"
    echo "  --help               Display this help message"
    echo "  --js-tests           Check JavaScript test suite"
    echo "  --lint-commitlint    Check linting of commit messages"
    echo "  --lint-hadolint      Check linting of Dockerfiles"
    echo "  --lint-jsonlint      Check linting of JSON files"
    echo "  --lint-js            Check linting of JavaScript code"
    echo "  --lint-shellcheck    Check linting of shell scripts"
}

if [ $# -eq 0 ]; then
    all
    exit 0
fi

arg="$1"
case $arg in
--all) all ;;
--help) help ;;
--docker-build) docker_build ;;
--docs-sphinx) docs_sphinx ;;
--format-prettier) format_prettier ;;
--js-tests) js_tests ;;
--lint-commitlint) lint_commitlint "$@" ;;
--lint-hadolint) lint_hadolint ;;
--lint-jsonlint) lint_jsonlint ;;
--lint-js) lint_js ;;
--lint-shellcheck) lint_shellcheck ;;
*) echo "[ERROR] Invalid argument '$arg'. Exiting." && help && exit 1 ;;
esac
